"use server";

import { revalidatePath } from "next/cache";

import { createAdminClient } from "@/lib/supabase/admin";
import { hasSupabasePublicConfig } from "@/lib/env";
import { bookingFormSchema, type BookingFormValues } from "@/lib/validators/booking";
import type {
  BookingActionState,
  BookingFieldErrors,
} from "@/types/booking";

/**
 * Public lead submission.
 *
 * Validate (never trust the client) → upsert customer → attach emergency
 * contact → create the booking (status defaults to "New", reference + activity
 * log generated by the database) → revalidate the admin dashboard so the lead
 * shows up instantly.
 *
 * Runs with the service-role key on the server only; RLS blocks the browser
 * from touching these tables directly.
 */
export async function createBooking(
  values: BookingFormValues,
): Promise<BookingActionState> {
  // 1 ─ Validate + normalize.
  const parsed = bookingFormSchema.safeParse(values);
  if (!parsed.success) {
    const fieldErrors: BookingFieldErrors = {};
    for (const issue of parsed.error.issues) {
      const key = issue.path[0] as keyof BookingFieldErrors | undefined;
      if (key && !fieldErrors[key]) fieldErrors[key] = issue.message;
    }
    return {
      status: "error",
      message: "Please fix the highlighted fields and try again.",
      fieldErrors,
    };
  }

  if (!hasSupabasePublicConfig() || !process.env.SUPABASE_SERVICE_ROLE_KEY) {
    return {
      status: "error",
      message:
        "Booking service isn't configured yet. Please add your Supabase keys (.env.local).",
    };
  }

  const { customer, emergencyContact, booking } = parsed.data;

  try {
    const supabase = createAdminClient();

    // 2 ─ Upsert the customer (dedupe on phone — the booking service's identity
    //     key; phone is now globally unique here too, in +91 E.164).
    const { data: customerRow, error: customerError } = await supabase
      .from("customers")
      .upsert(
        {
          name: customer.name,
          phone: customer.phone,
          email: customer.email,
          address: customer.address,
        },
        { onConflict: "phone" },
      )
      .select("id")
      .single();

    if (customerError || !customerRow) {
      throw customerError ?? new Error("Failed to save customer");
    }

    const customerId = customerRow.id;

    // 3 ─ Attach the emergency contact (avoid piling up duplicates).
    const { data: existingContact } = await supabase
      .from("emergency_contacts")
      .select("id")
      .eq("customer_id", customerId)
      .eq("contact_phone", emergencyContact.contactPhone)
      .maybeSingle();

    if (!existingContact) {
      const { error: contactError } = await supabase
        .from("emergency_contacts")
        .insert({
          customer_id: customerId,
          contact_name: emergencyContact.contactName,
          contact_phone: emergencyContact.contactPhone,
        });
      if (contactError) throw contactError;
    }

    // 4 ─ Create the booking (reference + activity log via DB triggers).
    const { data: bookingRow, error: bookingError } = await supabase
      .from("bookings")
      .insert({
        customer_id: customerId,
        start_datetime: booking.startDatetime,
        end_datetime: booking.endDatetime,
        total_hours: booking.totalHours,
        special_notes: booking.specialNotes,
        vehicle_interest: booking.vehicleInterest,
        preferred_slab_hours: booking.preferredSlabHours,
        is_unlimited_km: booking.isUnlimitedKm,
        unlimited_km_charge: booking.unlimitedKmCharge,
        estimated_amount: booking.estimatedAmount,
        status: "New",
      })
      .select("id, reference")
      .single();

    if (bookingError || !bookingRow) {
      throw bookingError ?? new Error("Failed to create booking");
    }

    // 5 ─ Push the new lead to the admin dashboard instantly.
    revalidatePath("/admin");
    revalidatePath("/admin/bookings");

    return {
      status: "success",
      reference: bookingRow.reference,
      bookingId: bookingRow.id,
      message: "Your booking request is in — we'll be in touch shortly.",
    };
  } catch (error) {
    console.error("[createBooking]", error);
    return {
      status: "error",
      message:
        "Something went wrong on our end. Please try again, or reach us on WhatsApp.",
    };
  }
}
